name: aimm-local-build

on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' # This line ensures submodules are initialized and updated

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common wget apt-transport-https gpg-agent
          sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y clang-12 libopencv-dev doxygen cmake

      - name: Install latest CMake
        run: |
          wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-Linux-x86_64.sh
          sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
          cmake --version

      - name: Install FlatBuffers compiler (flatc)
        run: |
          git clone https://github.com/google/flatbuffers.git
          cd flatbuffers
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          make -j2
          sudo make install

      - name: Run build script
        run: bash ./CREATE
        shell: bash
